# fly.toml app configuration file generated for hey-groot-api on 2023-06-15T03:37:09+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hey-groot-api"
primary_region = "hkg"
console_command = "/code/manage.py shell"

[deploy]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
